### ISSUE TITLE
Android: Map and Store Issue

### ISSUE THREAD

**Issue by Zenyuver** [AlteriaX/WuWa-Configs#11]
https://github.com/user-attachments/assets/4ee8911b-c576-4ac3-8216-9c81547e2928

It seems to be caused by DeviceProfile.ini
I tried the Very High and High configs together with Engine.ini and it always causes this unplayable bug

**Comment by AlteriaX** [comment]
Does it still happen on the latest config?

**Comment by Zenyuver** [comment]
> Does it still happen on the latest config?

No issues now
