### ISSUE TITLE
Does not support other card pool analysis tools.

### ISSUE THREAD

**Issue by HugoLau91** [AlteriaX/WuWa-Configs#12]
Such as the [WutheringWavesTool](https://github.com/leck995/WutheringWavesTool) .
Whether there are individual command lines that affect the tool accesses the card pool records？
![QQ截图20241102155900](https://github.com/user-attachments/assets/2d30c903-4b34-4082-ac3b-97141637d03e)
![QQ截图20241102155547](https://github.com/user-attachments/assets/0a06ac3a-8322-4550-8d36-d73813bbef51)

**Comment by AlteriaX** [comment]
Try deleting this from Engine.ini
```
[Core.Log]
global=none
```

**Comment by HugoLau91** [comment]
> Try deleting this from Engine.ini
> 
> ```
> [Core.Log]
> global=none
> ```

That's true!
