### ISSUE TITLE
WuWa 1.1: Alternative Upscaler With Configurable Internal Resolution

### ISSUE THREAD

**Issue by DiceTsuki** [AlteriaX/WuWa-Configs#3]
_Sorry for using the project's issue tracker instead of commenting on the Reddit's post. I can't leave a comment there due to my reddit account is still new (the sub's AutoMod didnt't like it)._

With Update 1.1 re-introducing FSR1, `r.ScreenPercentage` (primary [screen percentage](https://docs.unrealengine.com/4.26/en-US/RenderingAndGraphics/ScreenPercentage/)) was locked again from being changed using `Engine.ini`.

This [article](https://gpuopen.com/learn/ue4-fsr/) ([bonus](https://www.programmersought.com/article/921111291046/)) stated that activating TAAU using `r.TemporalAA.Upsampling` will override FSR1 (when `FSR ON` ingame), but i can't seem to see any difference (at 1600x900 resolution).

Even if it works, we're still stuck with `r.ScreenPercentage=77` (with `FSR ON`).

Alternatively, we can use FSR1 secondary screen percentage upscaler (make sure that you set `FSR OFF` ingame!):

    r.SecondaryScreenPercentage.GameViewport=90
    r.FidelityFX.FSR.SecondaryUpscale=1
    r.FidelityFX.FSR.MipBias.Method=2
    r.FidelityFX.FSR.MipBias.Offset=-2
    r.FidelityFX.FSR.RCAS.Sharpness=1.0

Some explanation:

    r.SecondaryScreenPercentage.GameViewport=90
Reduce internal screen resolution using secondary screen percentage, which unfortunately can't be anti-aliased with TAA.

The image won't be as good as using TAAU, But as long the value is not too low, it should still be ok.

    r.FidelityFX.FSR.SecondaryUpscale=1

Enables FSR1 secondary screen percentage upscaler.

    r.FidelityFX.FSR.MipBias.Method=2
    r.FidelityFX.FSR.MipBias.Offset=-2

Override `r.MipMapLODBias=0` set by `FSR OFF` (`FSR ON` use a different value) with your own value (change `-2`with your own).

Yep, `r.MipMapLODBias`can't be set directly in `Engine.ini` anymore.

    r.FidelityFX.FSR.RCAS.Sharpness=1.0

Apply sharpening after FSR upscale.

0.0 = sharpest.

Note:
` r.FidelityFX.FSR.MipBias.Method`, `r.FidelityFX.FSR.MipBias.Offset` and `r.FidelityFX.FSR.RCAS.Sharpness` works with `FSR ON`, and `FSR OFF` (if `r.FidelityFX.FSR.SecondaryUpscale=1`).

Extra:

Enable TAA Gen 5 with:

    r.TemporalAA.Algorithm=1
    r.TemporalAA.R11G11B10History=1

If there's too much aliasing.

Yep, i said earlier that TAA won't work with secondary screen percentage.

But hopefully with how blurry TAA Gen 5 is, we can at least reduce the aliasing effect on the downscaled image.

And you can tweak RCAS sharpness to mitigate the blur caused by it.

BTW, the 2nd CVar is for [TAA Gen 5 optimisation](https://forums.unrealengine.com/t/gen-5-temporal-anti-aliasing/152107/2), can omit it if you want.

**Comment by AlteriaX** [comment]
I've edited the post earlier about setting Anisotropic Filtering in GPU Control Panel, personally don't use the LOD Bias tweak for a while now cause it reduces FPS by a bit. TAA Gen 5 might look better but there's a lot of blurring in movement and ghosting on certain NPCs when they move, sharpening doesn't help. Wish there was a way to use TAA Upscaling on secondary screen percentage.

**Comment by DiceTsuki** [comment]
Sharpening is more on combatting the texture blur, especially on NPCs.

But yes, TAA Gen 5 has more ghosting than 4, especially for things moving near the border of the screen and swaying grasses.

But TAA Gen 4 flickers really annoys me, which really noticeable at lower resolution.

During 1.0, we can set `r.TemporalAASamples` to 2 or even 1 (but will have less to no AA) to reduce the flickering, unfortunately 1.1 force that CVar's value to 4. Even `r.TemporalAACurrentFrameWeight` can't be customised now.

So i'll use Gen 5 for now, which looks nice in cutscenes and less hectic scenes.

TBH i usually didn't notice the ghosting much unless i specially look for it.

Same can't be said for the flickering unfortunately.
