### ISSUE TITLE
Min req for `CPUParticlesPerEmitter` to enable Signal Particles

### ISSUE THREAD

**Issue by faustaahmad** [AlteriaX/WuWa-Configs#4]
Untested in game version 1.1
```ini
FX.MaxCPUParticlesPerEmitter=200
fx.MaxNiagaraCPUParticlesPerEmitter=200
```
Try to reduce by 1~10, if Signal Particles gone then it's still the same as game version 1.0
Thanks for sharing your configuration (No Reddit account)

**Comment by AlteriaX** [comment]
It's actually better to set it through fx.Niagara.QualityLevel instead, has similar effect to reduce particles but doesn't break stuff.
