### ISSUE TITLE
frame drop

### ISSUE THREAD

**Issue by HugoLau91** [AlteriaX/WuWa-Configs#6]
The new Engine.ini has encountered frame drops, which did not occur in the previous  and it shows that it's with 4070tis.

**Comment by AlteriaX** [comment]
Hmmm does it still happen after a few minutes? I'm not sure how long the shader creation takes, you can try removing the lines below and let me know.
```
r.CreateShadersOnLoad=1
niagara.CreateShadersOnLoad=1
```

**Comment by HugoLau91** [comment]
I replace back to the previous version of the Engine.ini, and then replace the new back, and the problem is solved, maybe the shader is created?

**Comment by AlteriaX** [comment]
Oh alright then, I'll see how it goes for the next few days and will update the Engine.ini if needed.
