### ISSUE TITLE
Skill animation dropped frame

### ISSUE THREAD

**Issue by AsukaSoryu0** [AlteriaX/WuWa-Configs#7]
It should be that this configuration change affects the frame count of the skill animation

a.URO.ForceAnimRate

I noticed in the latest file that this configuration changed from 2 to 1
If that's true, I don't think it's a good idea to lower the skill animation frame count, is it because the skill frame count is expensive?

**Comment by AlteriaX** [comment]
The game default is actually using 1 if I'm not mistaken, anyways what do you mean by changing from 2 to 1? It's back to 2 if you check the latest config.

**Comment by AsukaSoryu0** [comment]
> Sorry, my English is not very good. Let me re-describe the problem I encountered.
> I found that in your previous configuration file it was set to 1 about 'a.URO.ForceAnimRate', and in the latest change it is 2. When it was set to 2, I found the problem when using the skill of jinhsi. The third normal attack had a serious frame drop, as if it was only 30 frames.
> Also, the frame rate of the flames emitted by the Annihilation Bird boss was very low. When I adjusted it to 1, the frame rate of the skill animation of jinhsi seemed to return to normal.
> So I'm a little confused.

**Comment by AlteriaX** [comment]
That's really odd, I just tried with 60FPS cap and the animation still looks fine for me. I'll just switch back the settings and won't touch it again, seems like it doesn't work well for some people.

**Comment by AsukaSoryu0** [comment]
yes tku
