### ISSUE TITLE
Dear developer, when will 120 frames be restored?

### ISSUE THREAD

**Issue by AsukaSoryu0** [AlteriaX/WuWa-Configs#9]
No 120 frames. I'm having a hard time.

**Comment by AlteriaX** [comment]
For now just edit the LocalStorage.db for that.

[https://www.reddit.com/r/WutheringWaves/comments/1cyriwv/guide_to_improve_blurry_textureslod_with_image/](https://www.reddit.com/r/WutheringWaves/comments/1cyriwv/guide_to_improve_blurry_textureslod_with_image/)

**Comment by AsukaSoryu0** [comment]
> For now just edit the LocalStorage.db for that.
> 
> https://www.reddit.com/r/WutheringWaves/comments/1cyriwv/guide_to_improve_blurry_textureslod_with_image/

Does that mean no more mods? Because the previous mod also unlocked some configuration and performance optimization role

**Comment by AlteriaX** [comment]
For now no, don't know how to bypass the pak file signature verification.

**Comment by Dramorian** [comment]
> For now no, don't know how to bypass the pak file signature verification.

RE-UE4SS won't help here?

**Comment by AlteriaX** [comment]
Yes that one is detectable, meant to be used with private server only.
